### ISSUE TITLE
homebrew warning : Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by victou** [jolicode/pomdok#6]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the jolicode/pomdok tap (not Homebrew/brew or Homebrew/core):
 /usr/local/Homebrew/Library/Taps/jolicode/homebrew-pomdok/Formula/pomdok.rb:6

**Comment by Korbeil** [comment]
Fixed by https://github.com/jolicode/pomdok/releases/tag/v1.2.1
